config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :clubs do
    resources :events do
      resources :series do
        resources :matches, only: [:edit, :update]
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/club.rb
class Club < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :users
  validates :name, presence: true, uniqueness: true
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: %i[ show edit update destroy ]

  # GET /clubs or /clubs.json
  def index
    # @clubs = Club.all.where(user: current_user)
    @clubs = Club.all
  end

  # GET /clubs/1 or /clubs/1.json
  def show
    @events = Event.all
    @club = Club.find(params[:id])
  end

  # GET /clubs/new
  def new
    @club = Club.new
    @event = Event.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs or /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: "#{@club.name} a été créé." }
        # format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1 or /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: "#{@club.name} a été modifié." }
        # format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1 or /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: "#{@club.name} a été supprimé." }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def club_params
      params.require(:club).permit(:name)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= simple_form_for [@club] do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clubs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Club', new_club_path %>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @club.name %></h2>

<p>photo</p>

<p>Saison en cours</p>
<p>Classement saison 2021</p>
<p>Ajouter un événement</p>
<p>Tous les événements du club</p>
<p>Approuver un membre</p>

<%= link_to 'Show', club_event_path(@club) %> |
<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %> |
<%= link_to 'New Event', new_club_event_path(@club) %>