config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :clubs do
    resources :events do
      resources :series do
        resources :matches, only: [:edit, :update]
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    TYPE = %w(Saison Tournoi)
    belongs_to :club
    has_many :series
    validates :name, presence: true
    validates :winning_points, presence: true
    validates :loosing_points, presence: true
    validates :draw_points , presence: true
    validates :event_type, inclusion: { in: TYPE}, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @club = Club.find(params[:club_id])
    @events  = Event.where(club: @club)
  end

  # GET /events/1 or /events/1.json
  def show
    @club = Club.find(params[:club_id])
  end

  # GET /events/new
  def new
    @club = Club.find(params[:club_id])
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @club = Club.find(params[:club_id])
  end

  # POST /events or /events.json
  def create
    @club = Club.find(params[:club_id])
    @event = Event.new(event_params)
    @event.club = @club
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event.club, notice: "#{@event.name} a été créé." }
        # format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to club_events_path, notice: "#{@event.name} a été modifié." }
        # format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @club = Club.find(params[:club_id])
    @event = Event.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to club_events_path, notice: "#{@event.name} a été supprimé." }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :event_type, :winning_points, :loosing_points, :presence_points, :draw_points)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for [@club, @event] do |f| %>
  <%= f.input :name %>
  <%= f.input :event_type, as: :select, collection: Event::TYPE%>
  <%= f.input :beginning_date %>
  <%= f.input :winning_points %>
  <%= f.input :loosing_points %>
  <%= f.input :presence_points %>
  <%= f.input :draw_points %>
  <%= f.button :submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Modifier l'événemenr</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', club_event_path %> |
<%= link_to 'Back', club_events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vos événements</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

 <!-- Carousel -->
  <h2>Saison</h2>
  <h2>Tournois</h2>

  <tbody>
    <% @events.each do |event| %>
      <td><%=event.name %></td>
      <td><%= link_to 'Show', club_event_path(@club , event) %></td>
      <td><%= link_to 'Edit', edit_club_event_path(@club, event) %></td>
      <td><%= link_to 'Destroy', club_event_path(@club , event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_club_event_path %>

app/views/events/new.html.erb
<h1>Créer un evénement</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', club_events_path(@club) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<h1> <%= @event.name %> </h1>
<p>Date: <%= @event.beginning_date %></p>
<p>Status: en cours</p>

<p>22 participants Détails</p>
<p>7 séries terminées</p>

<h2>Règles</h2>

<p>Victoire 3 pts</p>
<p>Egalité 1 pt</p>
<p>Défaite 0 pt</p>
<p>Présence 1 pt</p>

<h2>Voir le classement</h2>
<h2>Ajouter une série</h2>
<h2>Clôturer l'événement</h2>



<%= link_to 'Edit', edit_club_event_path(@event) %> |
<%= link_to 'New', new_club_event_series_path(@club, @event) %> |
<%= link_to 'Back', club_events_path(@club) %>