config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :clubs do
    resources :events do
      resources :series do
        resources :matches, only: [:edit, :update]
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    @club = Club.find(params[:club_id])
    @event = Event.find(params[:event_id])
    @series = Serie.where(event: @event)
  end

  # GET /series/1 or /series/1.json
  def show
    @club = Club.find(params[:club_id])
    @event = Event.find(params[:event_id])
    @serie = Serie.find(params[:id])
    @matches = Match.where(serie: @serie)
  end

  # GET /series/new
  def new
    @serie = Serie.new
    @club = Club.find(params[:club_id])
    @event = Event.find(params[:event_id])
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @event = Event.find(params[:event_id])
    @serie = Serie.new(serie_params)
    @serie.event = @event
    @series = Serie.all

    respond_to do |format|
      if @serie.save
        @match = Match.new(court_number: 1, serie_id: @serie.id, player1: 0, player2: 1, player3: 2)
        @match.save!
        format.html { redirect_to club_event_series_index_path, notice: "La mêlée du #{Series.date} a été créée." }
        # format.json { render :show, status: :created, location: @serie }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @serie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: "La mêlée du #{Series.date} a été modifiée." }
        # format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_url, notice: "La mêlée du #{Series.date} a été supprimée." }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @serie = Serie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def serie_params
      params.require(:serie).permit(:event_id, :date, :number_of_courts, :players_presents, :duration, :number_courts)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= simple_form_for :serie, url: club_event_series_index_path(@club, @event, @serie) do |f| %>
  <%= f.input :date %>
  <%= f.input :players_presents %>
  <%= f.input :number_of_courts %>
  <%= f.input :duration %>
  <%= f.button :submit %>
<% end %>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_path %>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mêlées - <%= @event.name %></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
       <td> <%= link_to 'show', club_event_series_path(@club, @event, series) %> </td>
        <!-- link_to 'Show', club_event_series_path(@club, @event, @serie) -->
        <!-- link_to 'Edit', edit_series_path(series) -->
        <!-- link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } -->
      </tr>
    <% end %>

    <%= link_to 'New Serie', new_club_event_series_path %>
  </tbody>
</table>

<br>

app/views/series/new.html.erb
<h1>Ajouter une mêlée - <%= @event.name %></h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', club_event_series_index_path(@club, @event)  %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Les match de la serie (serie ID) du (serie date)</h1>

<h2>Match</h2>
<% @matches.each do |match| %>
  <%= match.serie_id %>
  <%= link_to 'Edit', edit_club_event_series_match_path(@club, @event, @serie, match) %>
<% end %>


<%# <%= link_to 'Back', series_path %>